export const prerequisiteTerms = [
  "Basic JavaScript knowledge",
  "Familiarity with React",
  "HTML and CSS fundamentals",
  "Understanding of data structures",
  "Experience with front-end frameworks",
  "Basic knowledge of web development",
  "Understanding of object-oriented programming",
  "Familiarity with version control (e.g., Git)",
  "Experience with database systems",
  "Knowledge of responsive web design",
  "Understanding of RESTful APIs",
  "Basic understanding of algorithms",
  "Familiarity with asynchronous programming",
  "Experience with package managers (e.g., npm)",
  "Knowledge of testing frameworks",
  "Understanding of design principles",
  "Experience with command-line tools",
  "Familiarity with web security best practices",
  "Understanding of performance optimization",
  "Experience with cloud services (e.g., AWS)",
  "Knowledge of SEO concepts",
  "Understanding of cross-browser compatibility",
  "Experience with mobile app development",
  "Familiarity with user experience (UX) design",
  "Knowledge of build tools (e.g., Webpack)",
  "Understanding of software development lifecycle",
  "Experience with web accessibility",
  "Basic understanding of server-side scripting",
  "Familiarity with responsive frameworks (e.g., Bootstrap)",
  "Knowledge of continuous integration (CI/CD)",
  "Experience with data visualization libraries",
  "Understanding of data analysis and statistics",
  "Knowledge of machine learning fundamentals",
  "Experience with cloud computing platforms (e.g., AWS, GCP)",
  "Understanding of blockchain technology",
  "Familiarity with artificial intelligence (AI)",
  "Knowledge of cybersecurity principles",
  "Experience with mobile app security",
  "Understanding of big data technologies",
  "Familiarity with IoT (Internet of Things) concepts",
  "Knowledge of virtual reality (VR) development",
  "Experience with augmented reality (AR) development",
  "Understanding of game development fundamentals",
  "Familiarity with 3D modeling and animation",
  "Knowledge of software architecture design patterns",
  "Experience with DevOps and containerization",
];
